<?php
declare(strict_types=1);

use Cms\Admin\Http\AdminAjaxRouter;
use Cms\Admin\Http\Ajax\Comments\BulkHandler as CommentsBulkHandler;
use Cms\Admin\Http\Ajax\Comments\DeleteHandler as CommentsDeleteHandler;
use Cms\Admin\Http\Ajax\Comments\ReplyHandler as CommentsReplyHandler;
use Cms\Admin\Http\Ajax\Comments\StatusHandler as CommentsStatusHandler;
use Cms\Admin\Http\Ajax\Media\DeleteHandler as MediaDeleteHandler;
use Cms\Admin\Http\Ajax\Media\EditorUploadHandler as MediaEditorUploadHandler;
use Cms\Admin\Http\Ajax\Media\LibraryHandler as MediaLibraryHandler;
use Cms\Admin\Http\Ajax\Media\OptimizeHandler as MediaOptimizeHandler;
use Cms\Admin\Http\Ajax\Media\UploadHandler as MediaUploadHandler;
use Cms\Admin\Http\Ajax\Navigation\CreateItemHandler as NavigationCreateItemHandler;
use Cms\Admin\Http\Ajax\Navigation\CreateMenuHandler as NavigationCreateMenuHandler;
use Cms\Admin\Http\Ajax\Navigation\DeleteItemHandler as NavigationDeleteItemHandler;
use Cms\Admin\Http\Ajax\Navigation\DeleteMenuHandler as NavigationDeleteMenuHandler;
use Cms\Admin\Http\Ajax\Navigation\UpdateItemHandler as NavigationUpdateItemHandler;
use Cms\Admin\Http\Ajax\Navigation\UpdateMenuHandler as NavigationUpdateMenuHandler;
use Cms\Admin\Http\Ajax\PostsAutosaveHandler;
use Cms\Admin\Http\Ajax\Settings\GeneralSaveHandler as SettingsGeneralSaveHandler;
use Cms\Admin\Http\Ajax\Settings\MailSaveHandler as SettingsMailSaveHandler;
use Cms\Admin\Http\Ajax\Settings\MailTestHandler as SettingsMailTestHandler;
use Cms\Admin\Http\Ajax\Settings\PermalinksSaveHandler as SettingsPermalinksSaveHandler;
use Cms\Admin\Http\Ajax\Users\BulkDeleteHandler as UsersBulkDeleteHandler;
use Cms\Admin\Http\Ajax\Users\DeleteHandler as UsersDeleteHandler;
use Cms\Admin\Http\Ajax\Users\SaveHandler as UsersSaveHandler;
use Cms\Admin\Http\Ajax\Users\SendTemplateHandler as UsersSendTemplateHandler;
use Cms\Admin\Http\Ajax\Users\ToggleHandler as UsersToggleHandler;

$router = AdminAjaxRouter::instance();
$router->register('posts_autosave', new PostsAutosaveHandler());
$router->register('media_upload', new MediaUploadHandler());
$router->register('media_delete', new MediaDeleteHandler());
$router->register('media_optimize', new MediaOptimizeHandler());
$router->register('media_library', new MediaLibraryHandler());
$router->register('media_editor_upload', new MediaEditorUploadHandler());
$router->register('comments_bulk', new CommentsBulkHandler());
$router->register('comments_status', new CommentsStatusHandler());
$router->register('comments_delete', new CommentsDeleteHandler());
$router->register('comments_reply', new CommentsReplyHandler());
$router->register('users_save', new UsersSaveHandler());
$router->register('users_bulk_delete', new UsersBulkDeleteHandler());
$router->register('users_delete', new UsersDeleteHandler());
$router->register('users_toggle', new UsersToggleHandler());
$router->register('users_send_template', new UsersSendTemplateHandler());
$router->register('settings_save', new SettingsGeneralSaveHandler());
$router->register('settings_mail_save', new SettingsMailSaveHandler());
$router->register('settings_mail_test', new SettingsMailTestHandler());
$router->register('settings_permalinks_save', new SettingsPermalinksSaveHandler());
$router->register('navigation_create_menu', new NavigationCreateMenuHandler());
$router->register('navigation_update_menu', new NavigationUpdateMenuHandler());
$router->register('navigation_delete_menu', new NavigationDeleteMenuHandler());
$router->register('navigation_create_item', new NavigationCreateItemHandler());
$router->register('navigation_update_item', new NavigationUpdateItemHandler());
$router->register('navigation_delete_item', new NavigationDeleteItemHandler());
